INSERT INTO Users (firstname, lastname, username, gender, description, email, password) VALUES
('John', 'Doe', 'johndoe', 'Male', 'A regular user', 'johndoe@example.com', 'password123'),
('Jane', 'Smith', 'janesmith', 'Female', 'Another regular user', 'janesmith@example.com', 'password123'),
('Alice', 'Johnson', 'alicejohnson', 'Female', 'Loves programming', 'alicej@example.com', 'password123'),
('Bob', 'Williams', 'bobwilliams', 'Male', 'Enjoys sports', 'bobwilliams@example.com', 'password123'),
('Charlie', 'Brown', 'charliebrown', 'Male', 'Enjoys reading books', 'charlieb@example.com', 'password123'),
('Diana', 'Davis', 'dianadavis', 'Female', 'A software developer', 'dianadavis@example.com', 'password123'),
('Eve', 'Martinez', 'evemartinez', 'Female', 'Enjoys music', 'evem@example.com', 'password123'),
('Frank', 'Garcia', 'frankgarcia', 'Male', 'Loves traveling', 'frankg@example.com', 'password123'),
('Grace', 'Hernandez', 'gracehernandez', 'Female', 'Travel blogger', 'graceh@example.com', 'password123'),
('Harry', 'Lopez', 'harrylopez', 'Male', 'Photographer', 'harryl@example.com', 'password123'),
('Ivy', 'Gonzalez', 'ivygonzalez', 'Female', 'Artist and designer', 'ivygonzalez@example.com', 'password123'),
('Jack', 'Wilson', 'jackwilson', 'Male', 'Tech enthusiast', 'jackw@example.com', 'password123'),
('Kathy', 'Anderson', 'kathyanderson', 'Female', 'Likes hiking', 'kathy@example.com', 'password123'),
('Leo', 'Thomas', 'leothomas', 'Male', 'Enjoys movies', 'leothomas@example.com', 'password123'),
('Megan', 'Jackson', 'meganjackson', 'Female', 'Loves nature', 'meganj@example.com', 'password123'),
('Nick', 'White', 'nickwhite', 'Male', 'Likes games', 'nickw@example.com', 'password123'),
('Olivia', 'Martin', 'oliviamartin', 'Female', 'Social media influencer', 'oliviam@example.com', 'password123'),
('Paul', 'Lee', 'paullee', 'Male', 'Web developer', 'paullee@example.com', 'password123'),
('Quinn', 'Perez', 'quinnperez', 'Female', 'Writer and editor', 'quinnperez@example.com', 'password123'),
('Rita', 'Clark', 'ritaclark', 'Female', 'Fashion enthusiast', 'ritac@example.com', 'password123');
