INSERT INTO Ratings (author_id, poem_id, stars, comment) VALUES
(1, 3, 4, 'Inspiring, but I was hoping for a bit more excitement.'),
(2, 6, 5, 'A perfect poem! I really related to it.'),
(3, 1, 3, 'Interesting approach, though a bit short.'),
(4, 4, 5, 'A poem that motivated me to face challenges.'),
(5, 8, 4, 'Good narrative, but could have gone into more depth.'),
(6, 2, 5, 'The best expression of imagination I''ve ever read.'),
(7, 12, 3, 'A good poem, but it lacked some spark.'),
(8, 14, 5, 'It perfectly reflects the magic of cinema.'),
(9, 10, 4, 'Interesting perspective, especially in the colors.'),
(10, 16, 5, 'It made me think about games and their adventures.'),
(11, 18, 2, 'Didn''t connect much with the topic, but good technique.'),
(12, 20, 4, 'Good use of language and structure.'),
(13, 7, 5, 'The music and emotions combined perfectly.'),
(14, 11, 4, 'Creative and with an interesting artistic vision.'),
(15, 9, 3, 'Could have had a deeper message.'),
(16, 5, 5, 'Amazing, made me reflect on my love for books.'),
(17, 13, 4, 'Captured the serenity of nature beautifully.'),
(18, 15, 5, 'Amazing description of the changing of seasons.'),
(19, 17, 3, 'Interesting take on digital life.'),
(20, 19, 4, 'It reflected the writer''s passion with authenticity.'),
(10, 19, 5, 'Perfectly captures the art of photography and how it immortalizes moments.'),
(9, 17, 4, 'Very moving and well written, made me think about my own travel experiences.'),
(9, 18, 5, 'Exploring horizons is a beautiful way to show how the world calls us to adventure.'),
(8, 15, 4, 'A poem that captures the essence of travel, very evocative.'),
(8, 16, 5, 'A perfect way to reflect on travel memories!'),
(7, 13, 5, 'Beautiful ode to music, it really touched my heart.'),
(7, 14, 3, 'The topic is interesting, but the poem could have been deeper.'),
(6, 11, 4, 'A poem celebrating art and creativity.'),
(6, 12, 5, 'Excellent humor for a programmer, made me laugh a lot!'),
(5, 9, 4, 'A tribute to books that captures the magic of reading.'),
(5, 10, 5, 'I loved the emotional connection with the act of reading, truly inspiring.'),
(4, 7, 5, 'Excellent motivational poem about teamwork, really inspiring.'),
(4, 8, 3, 'A poem that celebrates team spirit, but with a somewhat simplistic approach.'),
(3, 5, 4, 'A beautiful tribute to literature, I loved the style.'),
(3, 6, 2, 'I didn''t connect with the subject, but the technique is impressive.'),
(2, 3, 3, 'Interesting mix of technology and poetry, though it could go deeper into emotion.'),
(2, 4, 4, 'A well-done reflection on the nature of life.'),
(1, 1, 4, 'A reflective poem that captures the essence of sunrise.'),
(1, 2, 5, 'Very inspiring, made me think about my own journey of self-discovery.'),
(10, 20, 4, 'A beautiful poem about diversity, although some points could be clearer.');
